<a href="https://colab.research.google.com/github/luiska147/telecom_x_1/blob/main/Desafio_Telecom_X_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data extraction

In [57]:
import requests
import pandas as pd

url = 'https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json'
response = requests.get(url)
data = response.json()
datos = pd.DataFrame(data)
datos.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [58]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [59]:
datos_normalizados = pd.json_normalize(data)

datos_normalizados

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

## Transform Data

In [60]:
datos_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

### Verify each column

In [61]:
for col in datos_normalizados.columns:
  print(f'Valores unicos en la columna {col}: {datos_normalizados[col].nunique()}')

  if datos_normalizados[col].nunique() < 50:
    print(datos_normalizados[col].unique())
    print('-' * 50)

Valores unicos en la columna customerID: 7267
Valores unicos en la columna Churn: 3
['No' 'Yes' '']
--------------------------------------------------
Valores unicos en la columna customer.gender: 2
['Female' 'Male']
--------------------------------------------------
Valores unicos en la columna customer.SeniorCitizen: 2
[0 1]
--------------------------------------------------
Valores unicos en la columna customer.Partner: 2
['Yes' 'No']
--------------------------------------------------
Valores unicos en la columna customer.Dependents: 2
['Yes' 'No']
--------------------------------------------------
Valores unicos en la columna customer.tenure: 73
Valores unicos en la columna phone.PhoneService: 2
['Yes' 'No']
--------------------------------------------------
Valores unicos en la columna phone.MultipleLines: 3
['No' 'Yes' 'No phone service']
--------------------------------------------------
Valores unicos en la columna internet.InternetService: 3
['DSL' 'Fiber optic' 'No']
--------------------------------------------------
Valores unicos en la columna internet.OnlineSecurity: 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
Valores unicos en la columna internet.OnlineBackup: 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
Valores unicos en la columna internet.DeviceProtection: 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
Valores unicos en la columna internet.TechSupport: 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
Valores unicos en la columna internet.StreamingTV: 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
Valores unicos en la columna internet.StreamingMovies: 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
Valores unicos en la columna account.Contract: 3
['One year' 'Month-to-month' 'Two year']
--------------------------------------------------
Valores unicos en la columna account.PaperlessBilling: 2
['Yes' 'No']
--------------------------------------------------
Valores unicos en la columna account.PaymentMethod: 4
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
--------------------------------------------------
Valores unicos en la columna account.Charges.Monthly: 1585
Valores unicos en la columna account.Charges.Total: 6531

### Verify duplicated data

In [62]:
print('Numero de duplicados', datos_normalizados.duplicated().sum())

Numero de duplicados 0

### Verify null data

In [63]:
print('Numero de nulos ', datos_normalizados.isnull().sum())

Numero de nulos  customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

### Verify empty data

In [64]:
datos_normalizados.apply(lambda x: x.astype(str).str.strip() == '').sum()

customerID                     0
Churn                        224
customer.gender                0
customer.SeniorCitizen         0
customer.Partner               0
customer.Dependents            0
customer.tenure                0
phone.PhoneService             0
phone.MultipleLines            0
internet.InternetService       0
internet.OnlineSecurity        0
internet.OnlineBackup          0
internet.DeviceProtection      0
internet.TechSupport           0
internet.StreamingTV           0
internet.StreamingMovies       0
account.Contract               0
account.PaperlessBilling       0
account.PaymentMethod          0
account.Charges.Monthly        0
account.Charges.Total         11
dtype: int64

### Transform and fix data

In [65]:
datos_normalizados['account.Charges.Total'] = datos_normalizados['account.Charges.Total'].apply(pd.to_numeric, errors='coerce')
print(datos_normalizados['account.Charges.Total'].dtype)

float64

In [66]:
datos_normalizados = datos_normalizados[datos_normalizados['Churn'].str.strip() != '']
print('Número de filas despues de eliminar vacios en columna "Churn"', len(datos_normalizados))

Número de filas despues de eliminar vacios en columna "Churn" 7043

In [67]:
datos_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   object
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   object
 5   customer.Dependents        7043 non-null   object
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7032 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [68]:
datos_normalizados = datos_normalizados.dropna(subset = ['account.Charges.Total'])
print('Numero de nulos\n', datos_normalizados.isnull().sum())

Numero de nulos
 customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

In [69]:
datos_normalizados['Cuentas diarias'] = datos_normalizados['account.Charges.Monthly']/30
datos_normalizados

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,Cuentas diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60,1.966667

In [70]:
datos_normalizados = datos_normalizados.rename(columns={
    'customerID': 'Id Cliente',
    'customer.gender': 'Genero',
    'customer.SeniorCitizen': 'Adulto Mayor',
    'customer.Partner': 'Tiene Pareja',
    'customer.Dependents': 'Tiene Dependientes',
    'customer.tenure': 'Meses de contrato',
    'phone.PhoneService': 'Tiene Servicio Telefonico',
    'phone.MultipleLines': 'Tiene Multiples Lineas',
    'internet.InternetService': 'Tiene Servicio de Internet',
    'internet.OnlineSecurity': 'Contrato OnlineSecurity',
    'internet.OnlineBackup': 'Contrato OnlineBackup',
    'internet.DeviceProtection': 'Contrato DeviceProtecion',
    'internet.TechSupport': 'Contrato TechSupport',
    'internet.StreamingTV': 'Contrato StreamingTV',
    'internet.StreamingMovies': 'Contrato StreamingMovies',
    'account.Contract': 'Tipo de contrato',
    'account.PaperlessBilling': 'Tiene Facturación Electronica',
    'account.PaymentMethod': 'Metodo de Pago',
    'account.Charges.Monthly': 'Cargos Mensuales',
    'account.Charges.Total': 'Cargos Totales'
})
datos_normalizados

,Id Cliente,Churn,Genero,Adulto Mayor,Tiene Pareja,Tiene Dependientes,Meses de contrato,Tiene Servicio Telefonico,Tiene Multiples Lineas,Tiene Servicio de Internet,Contrato OnlineSecurity,Contrato OnlineBackup,Contrato DeviceProtecion,Contrato TechSupport,Contrato StreamingTV,Contrato StreamingMovies,Tipo de contrato,Tiene Facturación Electronica,Metodo de Pago,Cargos Mensuales,Cargos Totales,Cuentas diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60,1.966667

In [73]:
mapeo_binario = {
    'Yes': 1,
    'No': 0,
    'No internet service': 0,
    'No phone service': 0
}
columnas_binarias = [
    'Churn',
    'Tiene Pareja',
    'Tiene Dependientes',
    'Tiene Servicio Telefonico',
    'Tiene Multiples Lineas',
    'Contrato OnlineSecurity',
    'Contrato OnlineBackup',
    'Contrato DeviceProtecion',
    'Contrato TechSupport',
    'Contrato StreamingTV',
    'Contrato StreamingMovies',
    'Tiene Facturación Electronica'
]
datos_normalizados[columnas_binarias] = datos_normalizados[columnas_binarias].replace(mapeo_binario).astype(int)
datos_normalizados

,Id Cliente,Churn,Genero,Adulto Mayor,Tiene Pareja,Tiene Dependientes,Meses de contrato,Tiene Servicio Telefonico,Tiene Multiples Lineas,Tiene Servicio de Internet,Contrato OnlineSecurity,Contrato OnlineBackup,Contrato DeviceProtecion,Contrato TechSupport,Contrato StreamingTV,Contrato StreamingMovies,Tipo de contrato,Tiene Facturación Electronica,Metodo de Pago,Cargos Mensuales,Cargos Totales,Cuentas diarias
0,0002-ORFBO,0,Female,0,1,1,9,1,0,DSL,0,1,0,1,1,0,One year,1,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,0,Male,0,0,0,9,1,1,DSL,0,0,0,0,0,1,Month-to-month,0,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,1,Male,0,0,0,4,1,0,Fiber optic,0,0,1,0,0,0,Month-to-month,1,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,1,Male,1,1,0,13,1,0,Fiber optic,0,1,1,0,1,1,Month-to-month,1,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,1,Female,1,1,0,3,1,0,Fiber optic,0,0,0,1,1,0,Month-to-month,1,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,0,Female,0,0,0,13,1,0,DSL,1,0,0,1,0,0,One year,0,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,1,Male,0,1,0,22,1,1,Fiber optic,0,0,0,0,0,1,Month-to-month,1,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,0,Male,0,0,0,2,1,0,DSL,0,1,0,0,0,0,Month-to-month,1,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,0,Male,0,1,1,67,1,0,DSL,1,0,1,1,0,1,Two year,0,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,0,Male,0,1,1,63,0,0,DSL,1,1,1,0,1,1,Two year,0,Electronic check,59.00,3707.60,1.966667